# Generated by Django 5.2.7 on 2025-12-08 21:23

import apps.users.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=150, unique=True, validators=[apps.users.validators.validate_email_domain], verbose_name='Email address')),
                ('name', models.CharField(max_length=150, verbose_name='User name')),
                ('password', models.CharField(help_text="User's hash representation of the password", max_length=254, validators=[apps.users.validators.validate_password], verbose_name='Password')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=20, verbose_name='User role')),
                ('is_admin', models.BooleanField(default=False, help_text='True if the user is an admin and has an access to the admin panel', verbose_name='Admin status')),
                ('is_active', models.BooleanField(default=True, help_text='True if the user is active and has an access to request data', verbose_name='Active status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
