# Generated by Django 5.2.7 on 2025-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='True if the user is an admin and has an access to the admin panel', verbose_name='Staff status'),
        ),
    ]
